# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    choco install docfx -y
    docfx build -o ./publish
    if ($lastexitcode -ne 0){
      throw ("Error generating documentation")
    }
  displayName: "Docfx Build"

- task: CopyFiles@2
  inputs:
    SourceFolder: './publish/_site'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- powershell: cp "CI/manifest-staging.yml" "$(Build.ArtifactStagingDirectory)/manifest-staging.yml"
  displayName: "Copy staging manifest"

- powershell: cp "CI/manifest-prod.yml" "$(Build.ArtifactStagingDirectory)/manifest-prod.yml"
  displayName: "Copy prod manifest"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'