---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documentation
  template:
    metadata:
      labels:
        app: documentation
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: documentation
        image: steeltoe.azurecr.io/documentation
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: documentation
spec:
  ports:
  - port: 80
  selector:
    app: documentation