---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentation
  namespace: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documentation
  template:
    metadata:
      labels:
        app: documentation
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: documentation
          image: steeltoe.azurecr.io/documentation
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: documentation
  namespace: website
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: documentation
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: documentation
  namespace: website
spec:
  virtualhost:
    fqdn: docs-dev.steeltoe.io
    tls:
      secretName: website-tls
  routes:
    - conditions:
      - prefix: /
      services:
        - name: documentation
          port: 80
