---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentation
  namespace: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documentation
  template:
    metadata:
      labels:
        app: documentation
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: documentation
          image: steeltoe.azurecr.io/documentation
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: documentation
  namespace: website
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: documentation
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: documentation
  namespace: website
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: website-tls
    hosts:
    - docs-dev.steeltoe.io
  rules:
  - host: docs-dev.steeltoe.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: documentation
            port:
              number: 80
